name: "Setup Playwright"
description: "Setup Playwright with caching"
runs:
  using: "composite"
  steps:
    - name: Extract Playwright version
      id: playwright-version
      shell: bash
      run: echo "PLAYWRIGHT_VERSION=$(jq -r '.packages["node_modules/@playwright/test"].version' package-lock.json)" >> $GITHUB_ENV

    - name: Cache Playwright
      id: playwright-cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ env.PLAYWRIGHT_VERSION }}

    - name: Install Playwright Browsers
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      run: npx playwright install --with-deps --only-shell

    - name: Install Playwright's system dependencies
      if: steps.playwright-cache.outputs.cache-hit == 'true'
      shell: bash
      run: npx playwright install-deps