name: test

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.4.3"

    - name: build
      run: |
        make

    - name: test
      run: |
        make test

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: moneymoney-sankey
        path: dist/SankeyChart.lua