name: Verify Lua Script

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - uses: Rathoz/gh-actions-lua@patch-1
      with:
        luaVersion: "5.4"

    - name: build
      run: |
        make

    - name: test
      run: |
        make test

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: moneymoney-sankey
        path: dist/SankeyChart.lua