name: Verify Lua Script

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - uses: leafo/gh-actions-lua@v11
      with:
        luaVersion: "5.4"

    - name: Build
      run: make

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Test
      run: make test

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: moneymoney-sankey
        path: dist/SankeyChart.lua

    - name: Archive test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30